image: gradle:alpine

stages:
 - build
 - test

before_script:
 - chmod +x ./gradlew

build:
  stage: build
  script:
    ./gradlew --build-cache assemble

test:
  stage: test
  script:
    ./gradlew check

after_script:
 - echo "End CI"